#ifndef CODES_H_
#define CODES_H_

// PE machine type codes
#define IMAGE_FILE_MACHINE_UNKNOWN "IMAGE_FILE_MACHINE_UNKNOWN"
#define IMAGE_FILE_MACHINE_AM33 "IMAGE_FILE_MACHINE_AM33"
#define IMAGE_FILE_MACHINE_AMD64 "IMAGE_FILE_MACHINE_AMD64"
#define IMAGE_FILE_MACHINE_ARM "IMAGE_FILE_MACHINE_ARM"
#define IMAGE_FILE_MACHINE_ARMNT "IMAGE_FILE_MACHINE_ARMNT"
#define IMAGE_FILE_MACHINE_ARM64 "IMAGE_FILE_MACHINE_ARM64"
#define IMAGE_FILE_MACHINE_EBC "IMAGE_FILE_MACHINE_EBC"
#define IMAGE_FILE_MACHINE_I386 "IMAGE_FILE_MACHINE_I386"
#define IMAGE_FILE_MACHINE_IA64 "IMAGE_FILE_MACHINE_IA64"
#define IMAGE_FILE_MACHINE_M32R "IMAGE_FILE_MACHINE_M32R"
#define IMAGE_FILE_MACHINE_MIPS16 "IMAGE_FILE_MACHINE_MIPS16"
#define IMAGE_FILE_MACHINE_MIPSFPU "IMAGE_FILE_MACHINE_MIPSFPU"
#define IMAGE_FILE_MACHINE_MIPSFPU16 "IMAGE_FILE_MACHINE_MIPSFPU16"
#define IMAGE_FILE_MACHINE_POWERPC "IMAGE_FILE_MACHINE_POWERPC"
#define IMAGE_FILE_MACHINE_POWERPCFP "IMAGE_FILE_MACHINE_POWERPCFP"
#define IMAGE_FILE_MACHINE_R4000 "IMAGE_FILE_MACHINE_R4000"
#define IMAGE_FILE_MACHINE_SH3 "IMAGE_FILE_MACHINE_SH3"
#define IMAGE_FILE_MACHINE_SH3DSP "IMAGE_FILE_MACHINE_SH3DSP"
#define IMAGE_FILE_MACHINE_SH4 "IMAGE_FILE_MACHINE_SH4"
#define IMAGE_FILE_MACHINE_SH5 "IMAGE_FILE_MACHINE_SH5"
#define IMAGE_FILE_MACHINE_THUMB "IMAGE_FILE_MACHINE_THUMB"
#define IMAGE_FILE_MACHINE_WCEMIPSV2 "IMAGE_FILE_MACHINE_WCEMIPSV2"

// PE characteristics codes
#define IMAGE_FILE_RELOCS_STRIPPED "IMAGE_FILE_RELOCS_STRIPPED"
#define IMAGE_FILE_EXECUTABLE_IMAGE "IMAGE_FILE_EXECUTABLE_IMAGE"
#define IMAGE_FILE_LINE_NUMS_STRIPPED "IMAGE_FILE_NUMS_STRIPPED"
#define IMAGE_FILE_LOCAL_SYMS_STRIPPED "IMAGE_FILE_SYMS_STRIPPED"
#define IMAGE_FILE_AGGRESSIVE_WS_TRIM "IMAGE_FILE_AGGRESSIVE_WS_TRIM"
#define IMAGE_FILE_LARGE_ADDRESS_AWARE "IMAGE_FILE_LARGE_ADDRESS_AWARE"
#define IMAGE_FILE_BYTES_REVERSED_LO "IMAGE_FILE_BYTES_REVERSED_LO"
#define IMAGE_FILE_32BIT_MACHINE "IMAGE_FILE_32BIT_MACHINE"
#define IMAGE_FILE_DEBUG_STRIPPED "IMAGE_FILE_DEBUG_STRIPPED"
#define IMAGE_FILE_REMOVABLE_RUN_FROM_SWAP "IMAGE_FILE_REMOVEABLE_RUN_FROM_SWAP"
#define IMAGE_FILE_NET_RUN_FROM_SWAP "IMAGE_FILE_NET_RUN_FROM_SWAP"
#define IMAGE_FILE_SYSTEM "IMAGE_FILE_SYSTEM"
#define IMAGE_FILE_DLL "IMAGE_FILE_DLL"
#define IMAGE_FILE_UP_SYSTEM_ONLY "IMAGE_FILE_UP_SYSTEM_ONLY"
#define IMAGE_FILE_BYTES_REVERSED_HI "IMAGE_FILE_BYTES_REVERSED_HI"

// PE Windows subsystem codes
#define IMAGE_SUBSYSTEM_UNKNOWN "IMAGE_SUBSYSTEM_UNKNOWN"
#define IMAGE_SUBSYSTEM_NATIVE "IMAGE_SUBSYSTEM_NATIVE"
#define IMAGE_SUBSYSTEM_WINDOWS_GUI "IMAGE_SUBSYSTEM_WINDOWS_GUI"
#define IMAGE_SUBSYSTEM_WINDOWS_CUI "IMAGE_SUBSYSTEM_WINDOWS_CUI"
#define IMAGE_SUBSYSTEM_POSIX_CUI "IMAGE_SUBSYSTEM_POXIS_CUI"
#define IMAGE_SUBSYSTEM_WINDOWS_CE_GUI "IMAGE_SUBSYSTEM_WINDOWS_CE_GUI"
#define IMAGE_SUBSYSTEM_EFI_APPLICATION "IMAGE_SUBSYSTEM_EFI_APPLICATION"
#define IMAGE_SUBSYSTEM_EFI_BOOT_SERVICE_DRIVER "IMAGE_SUBSYSTEM_EFI_BOOT_SERVICE_DRIVER"
#define IMAGE_SUBSYSTEM_EFI_RUNTIME_DRIVER "IMAGE_SUBSYSTEM_EFI_RUNTIME_DRIVER"
#define IMAGE_SUBSYSTEM_EFI_ROM "IMAGE_SUBSYSTEM_EFI_ROM"
#define IMAGE_SUBSYSTEM_XBOX "IMAGE_SUBSYSTEM_XBOX"

// PE characteristics flag values
#define CHARACTERISTICS_RELOCS_STRIPPED 0x0001
#define CHARACTERISTICS_EXECUTABLE_IMAGE 0x0002
#define CHARACTERISTICS_LINE_NUMS_STRIPPED 0x0004
#define CHARACTERISTICS_LOCAL_SYMS_STRIPPED 0x0008
#define CHARACTERISTICS_AGGRESSIVE_WS_TRIM 0x0010
#define CHARACTERISTICS_LARGE_ADDRESS_AWARE 0x0020
#define CHARACTERISTICS_reserved 0x0040
#define CHARACTERISTICS_BYTES_REVERSED_LO 0x0080
#define CHARACTERISTICS_32BIT_MACHINE 0x0100
#define CHARACTERISTICS_DEBUG_STRIPPED 0x0200
#define CHARACTERISTICS_REMOVABLE_RUN_FROM_SWAP 0x0400
#define CHARACTERISTICS_NET_RUN_FROM_SWAP 0x0800
#define CHARACTERISTICS_SYSTEM 0x1000
#define CHARACTERISTICS_DLL 0x2000
#define CHARACTERISTICS_UP_SYSTEM_ONLY 0x4000
#define CHARACTERISTICS_BYTES_REVERSED_HI 0x8000

#endif // CODES_H_